'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campus
    Public Property CampusID As Integer
    Public Property TenantID As System.Guid
    Public Property PartyID As Nullable(Of Integer)
    Public Property CompanyID As Nullable(Of Integer)
    Public Property GSTRegID As Nullable(Of Integer)
    Public Property DispName As String
    Public Property TCName As String
    Public Property CampusType As String
    Public Property PIDUnitID As Nullable(Of Integer)
    Public Property EmailPur As String
    Public Property EmailSls As String
    Public Property EmailGen As String
    Public Property SeqMult As Nullable(Of Integer)
    Public Property SeqOffset As Nullable(Of Integer)
    Public Property AccountMapCode As String
    Public Property PONote As String
    Public Property FactoryLicenseNumber As String
    Public Property HasPunches As Nullable(Of Boolean)
    Public Property AcceptsOrder As Nullable(Of Boolean)
    Public Property AcceptsEnq As Nullable(Of Boolean)
    Public Property DivisionID As Nullable(Of Integer)
    Public Property DivisionCodeList As String
    Public Property GeoAreaList As String
    Public Property CampusCode As String
    Public Property InvoiceNote As String

    Public Overridable Property GSTReg As GSTReg
    Public Overridable Property Party As Party
    Public Overridable Property EwayBill As ICollection(Of EwayBill) = New HashSet(Of EwayBill)
    Public Overridable Property Invoice As ICollection(Of Invoice) = New HashSet(Of Invoice)

End Class
