'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Company
    Public Property CompanyID As Integer
    Public Property TenantID As System.Guid
    Public Property MainPartyID As Nullable(Of Integer)
    Public Property CompName As String
    Public Property BrandName As String
    Public Property SalesEmpID As Nullable(Of Integer)
    Public Property PurchaseEmpID As Nullable(Of Integer)
    Public Property HOCampusID As Nullable(Of Integer)
    Public Property ESIReasons As String
    Public Property HRStartDate As Nullable(Of Date)
    Public Property FinStartDate As Nullable(Of Date)
    Public Property BonusStartMonth As Nullable(Of Integer)
    Public Property LeaveStartMonth As Nullable(Of Integer)
    Public Property CurrFinYearID As Nullable(Of Integer)
    Public Property CurrLeaveMasterID As Nullable(Of Integer)
    Public Property GratuityDaysPerYear As Nullable(Of Decimal)
    Public Property GratuityMinMonths As Nullable(Of Decimal)
    Public Property LeaveCashDaysYear As Nullable(Of Decimal)
    Public Property PrincipalEmpID As Nullable(Of Integer)
    Public Property Occupier As String
    Public Property CustCode As String
    Public Property PolicyNumGG As String
    Public Property PolicyNumEDLIP As String
    Public Property ARDGG As Nullable(Of Date)
    Public Property ARDEDLIP As Nullable(Of Date)
    Public Property LunchInterval As Nullable(Of Integer)
    Public Property Manager As String
    Public Property NatureIndustry As String
    Public Property EmploymentOffice As String
    Public Property MainShiftID As Nullable(Of Integer)
    Public Property AdvAttAvgMin As Nullable(Of Decimal)
    Public Property AdvLimitPercent As Nullable(Of Decimal)
    Public Property AdvanceDay As Nullable(Of Integer)
    Public Property AdvanceRequestDays As Nullable(Of Integer)
    Public Property TPCertLogo1 As Byte()
    Public Property LoanRules As String
    Public Property PANNum As String
    Public Property CINNum As String

    Public Overridable Property PartyMain As PartyMain
    Public Overridable Property Division As ICollection(Of Division) = New HashSet(Of Division)
    Public Overridable Property GSTReg As ICollection(Of GSTReg) = New HashSet(Of GSTReg)

End Class
