'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPInvoiceItem
    Public Property CPInvoiceItemID As Integer
    Public Property TenantID As System.Guid
    Public Property CPInvoiceID As Nullable(Of Integer)
    Public Property Description As String
    Public Property SortIndex As Nullable(Of Integer)
    Public Property TY As String
    Public Property TXVAL As Nullable(Of Decimal)
    Public Property RT As Nullable(Of Decimal)
    Public Property IAMT As Nullable(Of Decimal)
    Public Property CAMT As Nullable(Of Decimal)
    Public Property SAMT As Nullable(Of Decimal)
    Public Property CSAMT As Nullable(Of Decimal)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String

    Public Overridable Property CPInvoice As CPInvoice

End Class
