'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property CustomerID As Integer
    Public Property TenantID As System.Guid
    Public Property PartyID As Nullable(Of Integer)
    Public Property DocSysNum As Nullable(Of Integer)
    Public Property CustomerCode As String
    Public Property CustomerClass As String
    Public Property Remark As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property RegLastCorres As Nullable(Of Date)
    Public Property RegUserID As Nullable(Of System.Guid)
    Public Property RegPersPartyID As Nullable(Of Integer)
    Public Property RequireReg As Nullable(Of Boolean)
    Public Property RegDate As Nullable(Of Date)
    Public Property RegExp As Nullable(Of Date)
    Public Property STFPersPartyID As Nullable(Of Integer)
    Public Property TCAdd As String
    Public Property Account_Name As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastModApp As String
    Public Property ImportFileID As Nullable(Of System.Guid)

End Class
