'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Division
    Public Property DivisionID As Integer
    Public Property TenantID As System.Guid
    Public Property CompanyID As Nullable(Of Integer)
    Public Property DivisionCode As String
    Public Property DivisionName As String

    Public Overridable Property Company As Company

End Class
