'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EWayBillVehicle
    Public Property EWayBillVehicleID As Decimal
    Public Property TenantID As System.Guid
    Public Property EwayBillID As Nullable(Of Integer)
    Public Property EnteredDate As Nullable(Of Date)
    Public Property VehicleType As String
    Public Property VehicleNo As String
    Public Property FromPlace As String
    Public Property FromState As String
    Public Property ReasonCode As String
    Public Property TransDocNo As String
    Public Property TransDocDate As Nullable(Of Date)
    Public Property TransMode As Nullable(Of Integer)
    Public Property UserGSTINTransin As String
    Public Property TripshtNo As Nullable(Of Decimal)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String

    Public Overridable Property EwayBill As EwayBill

End Class
