'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EwayBill
    Public Property EwayBillID As Integer
    Public Property TenantID As System.Guid
    Public Property EwayBillNum As Nullable(Of Long)
    Public Property EwayBillDate As Nullable(Of Date)
    Public Property CampusID As Nullable(Of Integer)
    Public Property SupplyType As String
    Public Property SubSupplyType As String
    Public Property DocType As String
    Public Property DocumentID As Nullable(Of Integer)
    Public Property InvoiceID As Nullable(Of Integer)
    Public Property ODNoteID As Nullable(Of Integer)
    Public Property TransVendorID As Nullable(Of Integer)
    Public Property TransDistance As Nullable(Of Integer)
    Public Property NoValidDays As Nullable(Of Integer)
    Public Property ValidUpto As Nullable(Of Date)
    Public Property ewbRejectedDate As Nullable(Of Date)
    Public Property cancelDate As Nullable(Of Date)
    Public Property LastVehicleID As Nullable(Of Integer)
    Public Property fromAddr1 As String
    Public Property fromAddr2 As String
    Public Property fromPlace As String
    Public Property fromPinCode As Nullable(Of Integer)
    Public Property fromStateCode As Nullable(Of Integer)
    Public Property toAddr1 As String
    Public Property toAddr2 As String
    Public Property toPlace As String
    Public Property toPinCode As Nullable(Of Integer)
    Public Property toStateCode As Nullable(Of Integer)
    Public Property actFromStateCode As Nullable(Of Integer)
    Public Property actToStateCode As Nullable(Of Integer)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property transactionType As Nullable(Of Integer)
    Public Property dispatchFromGstin As String
    Public Property shipToGSTIN As String
    Public Property shipToTradeName As String
    Public Property otherValue As Nullable(Of Decimal)
    Public Property cessNonAdvolValue As Nullable(Of Decimal)
    Public Property ChallanID As Nullable(Of Integer)
    Public Property cessNonAdvolRT As Nullable(Of Decimal)
    Public Property dispatchFromTradeName As String
    Public Property SubSupplyDesc As String
    Public Property ReturnPeriodID As Nullable(Of Integer)
    Public Property DocNum As String
    Public Property DocDate As Nullable(Of Date)
    Public Property VendorID As Nullable(Of Integer)
    Public Property CustomerID As Nullable(Of Integer)
    Public Property VAL As Nullable(Of Decimal)
    Public Property Sply_Ty As String
    Public Property ImportFileID As Nullable(Of System.Guid)

    Public Overridable Property Campus As Campus
    Public Overridable Property EWayBillVehicle As ICollection(Of EWayBillVehicle) = New HashSet(Of EWayBillVehicle)

End Class
