'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FinYears
    Public Property FinYearID As Integer
    Public Property TenantID As System.Guid
    Public Property StDate As Nullable(Of Date)
    Public Property EnDate As Nullable(Of Date)
    Public Property Descrip As String

    Public Overridable Property PostPeriod As ICollection(Of PostPeriod) = New HashSet(Of PostPeriod)

End Class
