'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GstAdvanceVouch
    Public Property GstAdvanceVouchID As Integer
    Public Property TenantID As System.Guid
    Public Property CampusID As Nullable(Of Integer)
    Public Property DivisionID As Nullable(Of Integer)
    Public Property PaymentID As Nullable(Of Integer)
    Public Property InvoiceID As Nullable(Of Integer)
    Public Property CustomerID As Nullable(Of Integer)
    Public Property VendorID As Nullable(Of Integer)
    Public Property DocType As String
    Public Property AdvanceVouchType As String
    Public Property OrigVouchID As Nullable(Of Integer)
    Public Property RefundVouchID As Nullable(Of Integer)
    Public Property RootVouchID As Nullable(Of Integer)
    Public Property POSTaxAreaID As Nullable(Of Integer)
    Public Property ReturnPeriodID As Nullable(Of Integer)
    Public Property Dated As Nullable(Of Date)
    Public Property VouchNum As String
    Public Property Remark As String
    Public Property StatusNum As Nullable(Of Integer)
    Public Property IsAmendment As Nullable(Of Boolean)
    Public Property Sply_Ty As String
    Public Property AmountTot As Nullable(Of Decimal)
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property IsReturn As Nullable(Of Boolean)
    Public Property Diff_Percent As Nullable(Of Decimal)
    Public Property RCHRG As String
    Public Property SupplyFromTaxAreaID As Nullable(Of Integer)
    Public Property DocumentType As String
    Public Property ImportFileID As Nullable(Of System.Guid)
    Public Property PartyGstRegType As String
    Public Property VouchNumDynamicPart As Nullable(Of Long)
    Public Property InvoiceNumberTemplateId As Nullable(Of Integer)

    Public Overridable Property GstAdvanceVouchItem As ICollection(Of GstAdvanceVouchItem) = New HashSet(Of GstAdvanceVouchItem)

End Class
