'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GstAdvanceVouchItem
    Public Property GstAdvanceVouchItemID As Integer
    Public Property TenantID As System.Guid
    Public Property GstAdvanceVouchID As Nullable(Of Integer)
    Public Property LineSNum As Nullable(Of Integer)
    Public Property DiffAD_AMT As Nullable(Of Decimal)
    Public Property DiffIAMT As Nullable(Of Decimal)
    Public Property DiffSAMT As Nullable(Of Decimal)
    Public Property DiffCAMT As Nullable(Of Decimal)
    Public Property DiffCSAMT As Nullable(Of Decimal)
    Public Property AD_AMT As Nullable(Of Decimal)
    Public Property I_RT As Nullable(Of Decimal)
    Public Property C_RT As Nullable(Of Decimal)
    Public Property S_RT As Nullable(Of Decimal)
    Public Property RT As Nullable(Of Decimal)
    Public Property IAMT As Nullable(Of Decimal)
    Public Property CAMT As Nullable(Of Decimal)
    Public Property SAMT As Nullable(Of Decimal)
    Public Property CSAMT As Nullable(Of Decimal)
    Public Property GSTR3B31Section As String
    Public Property GSTR3B32Section As String
    Public Property GSTR3B5Section As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property Cess_Rt As Nullable(Of Decimal)
    Public Property RemarkItem As String

    Public Overridable Property GstAdvanceVouch As GstAdvanceVouch

End Class
