'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GSTReg
    Public Property GSTRegID As Integer
    Public Property TenantID As System.Guid
    Public Property CompanyID As Nullable(Of Integer)
    Public Property TaxAreaID As Nullable(Of Integer)
    Public Property GSTIN As String
    Public Property GSTNUserId As String
    Public Property ApplicationNum As String
    Public Property RegDate As Nullable(Of Date)
    Public Property SearchResult As String
    Public Property PartialCredit As Nullable(Of Boolean)
    Public Property AuthPAN As String
    Public Property EWBUserName As String
    Public Property EWBPassword As String
    Public Property TurnOver As Nullable(Of Decimal)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property GSTRegType As String

    Public Overridable Property Campus As ICollection(Of Campus) = New HashSet(Of Campus)
    Public Overridable Property Company As Company
    Public Overridable Property CPInvoice As ICollection(Of CPInvoice) = New HashSet(Of CPInvoice)
    Public Overridable Property TaxArea As TaxArea

End Class
