'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoiceItemGst
    Public Property InvoiceItemGSTID As Integer
    Public Property TenantID As System.Guid
    Public Property InvoiceID As Nullable(Of Integer)
    Public Property Description As String
    Public Property LineSNum As Nullable(Of Integer)
    Public Property TY As String
    Public Property Hsn_Sc As String
    Public Property TXVAL As Nullable(Of Decimal)
    Public Property I_RT As Nullable(Of Decimal)
    Public Property C_RT As Nullable(Of Decimal)
    Public Property S_RT As Nullable(Of Decimal)
    Public Property RT As Nullable(Of Decimal)
    Public Property IAMT As Nullable(Of Decimal)
    Public Property CAMT As Nullable(Of Decimal)
    Public Property SAMT As Nullable(Of Decimal)
    Public Property CSAMT As Nullable(Of Decimal)
    Public Property Uqc As String
    Public Property Qty As Nullable(Of Decimal)
    Public Property BasicRate As Nullable(Of Decimal)
    Public Property tx_i As Nullable(Of Decimal)
    Public Property tx_c As Nullable(Of Decimal)
    Public Property tx_s As Nullable(Of Decimal)
    Public Property tx_cs As Nullable(Of Decimal)
    Public Property elg As String
    Public Property GstTaxType As String
    Public Property Details As String
    Public Property GSTR3B31Section As String
    Public Property GSTR3B32Section As String
    Public Property GSTR3B5Section As String
    Public Property ChargeBeforeTax As Nullable(Of Decimal)
    Public Property DiscountBeforeTax As Nullable(Of Decimal)
    Public Property Cess_Rt As Nullable(Of Decimal)
    Public Property Hsn_Desc As String
    Public Property ITCReversal_4243 As Nullable(Of Boolean)
    Public Property ITCDate As Nullable(Of Date)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property GSTR3B4ASection As String
    Public Property GSTR3B4DSection As String
    Public Property RemarkItem As String

    Public Overridable Property Invoice As Invoice

End Class
