'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoice
    Public Property InvoiceID As Integer
    Public Property TenantID As System.Guid
    Public Property CampusID As Nullable(Of Integer)
    Public Property CDNInvoiceID As Nullable(Of Integer)
    Public Property OrigInvoiceID As Nullable(Of Integer)
    Public Property RootInvoiceID As Nullable(Of Integer)
    Public Property DivisionID As Nullable(Of Integer)
    Public Property CustomerID As Nullable(Of Integer)
    Public Property ConsigneePrefix As String
    Public Property VendorID As Nullable(Of Integer)
    Public Property ConsigneeID As Nullable(Of Integer)
    Public Property POSTaxAreaID As Nullable(Of Integer)
    Public Property ReturnPeriodID As Nullable(Of Integer)
    Public Property DocType As String
    Public Property GSTInvoiceType As String
    Public Property GSTInvoiceSubType As String
    Public Property Sply_Ty As String
    Public Property ExportDutyType As String
    Public Property BillOf As String
    Public Property RCHRG As String
    Public Property IsAmendment As Nullable(Of Boolean)
    Public Property InvoiceNum As String
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property VAL As Nullable(Of Decimal)
    Public Property StatusNum As Nullable(Of Integer)
    Public Property Remark As String
    Public Property ETIN As String
    Public Property SBPCode As String
    Public Property SBNUM As Nullable(Of Integer)
    Public Property SBDT As Nullable(Of Date)
    Public Property boe_num As String
    Public Property boe_dt As Nullable(Of Date)
    Public Property boe_val As Nullable(Of Decimal)
    Public Property port_code As String
    Public Property is_sez As String
    Public Property stin As String
    Public Property p_gst As String
    Public Property MatchCode As String
    Public Property Lastupdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property LastTransactionId As Nullable(Of System.Guid)
    Public Property ActionFlag As String
    Public Property Flag As String
    Public Property CFlag As String
    Public Property CPInvoiceID As Nullable(Of Integer)
    Public Property ShipFromTaxAreaID As Nullable(Of Integer)
    Public Property ShipToTaxAreaID As Nullable(Of Integer)
    Public Property UniqueKey As String
    Public Property Diff_Percent As Nullable(Of Integer)
    Public Property SaleBondedWH As Nullable(Of Boolean)
    Public Property Rsn As String
    Public Property CancelDate As Nullable(Of Date)
    Public Property IsForeignCurrency As Nullable(Of Boolean)
    Public Property Ex_Rt As Nullable(Of Decimal)
    Public Property PartyGstRegType As String
    Public Property TransactionType As String
    Public Property DocumentType As String
    Public Property ImportFileID As Nullable(Of System.Guid)
    Public Property gstn_status_cd As String
    Public Property gstn_error_cd As String
    Public Property gstn_error_msg As String
    Public Property IsCreditISD As Nullable(Of Boolean)
    Public Property InvoiceNumDynamicPart As Nullable(Of Long)
    Public Property InvoiceNumberTemplateId As Nullable(Of Integer)

    Public Overridable Property Campus As Campus
    Public Overridable Property InvoiceItemGst As ICollection(Of InvoiceItemGst) = New HashSet(Of InvoiceItemGst)

End Class
