'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class mxgstEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=mxgstEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Campus() As DbSet(Of Campus)
    Public Overridable Property Company() As DbSet(Of Company)
    Public Overridable Property CPInvoice() As DbSet(Of CPInvoice)
    Public Overridable Property CPInvoiceItem() As DbSet(Of CPInvoiceItem)
    Public Overridable Property Customer() As DbSet(Of Customer)
    Public Overridable Property Division() As DbSet(Of Division)
    Public Overridable Property EwayBill() As DbSet(Of EwayBill)
    Public Overridable Property EWayBillVehicle() As DbSet(Of EWayBillVehicle)
    Public Overridable Property FinYears() As DbSet(Of FinYears)
    Public Overridable Property GstAdvanceVouch() As DbSet(Of GstAdvanceVouch)
    Public Overridable Property GstAdvanceVouchItem() As DbSet(Of GstAdvanceVouchItem)
    Public Overridable Property GSTReg() As DbSet(Of GSTReg)
    Public Overridable Property Invoice() As DbSet(Of Invoice)
    Public Overridable Property InvoiceItemGst() As DbSet(Of InvoiceItemGst)
    Public Overridable Property Party() As DbSet(Of Party)
    Public Overridable Property PartyMain() As DbSet(Of PartyMain)
    Public Overridable Property PostPeriod() As DbSet(Of PostPeriod)
    Public Overridable Property TaxArea() As DbSet(Of TaxArea)
    Public Overridable Property ValidationRule() As DbSet(Of ValidationRule)
    Public Overridable Property Vendor() As DbSet(Of Vendor)

End Class
