'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PartyMain
    Public Property MainPartyID As Integer
    Public Property TenantID As System.Guid
    Public Property MPName As String
    Public Property PartyType As String
    Public Property PartySubType As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property StateCode As String
    Public Property Country As String
    Public Property CountryCode As String
    Public Property Pincode As String
    Public Property PhCountry As String
    Public Property PhArea As String
    Public Property FaxCountry As String
    Public Property FaxArea As String
    Public Property Phnum As String
    Public Property Faxnum As String
    Public Property Web As String
    Public Property Email As String
    Public Property SegmentOther As String
    Public Property SegmentID As Nullable(Of Integer)
    Public Property NumEmp As Nullable(Of Decimal)
    Public Property Description As String
    Public Property Area As String
    Public Property Field As String
    Public Property Remark As String
    Public Property IsDealer As Nullable(Of Boolean)
    Public Property IsEmployer As Nullable(Of Boolean)
    Public Property IsCompetitor As Nullable(Of Boolean)
    Public Property IsGovt As Nullable(Of Boolean)
    Public Property IsEPC As Nullable(Of Boolean)
    Public Property IsConsultant As Nullable(Of Boolean)
    Public Property IsContractor As Nullable(Of Boolean)
    Public Property IsEndUser As Nullable(Of Boolean)
    Public Property IsTrader As Nullable(Of Boolean)
    Public Property IsInspAgency As Nullable(Of Boolean)
    Public Property EstdIn As String
    Public Property MPNick As String
    Public Property NetName As String
    Public Property TCName As String
    Public Property TCLogo As Byte()
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property TurnOver As Nullable(Of Decimal)

    Public Overridable Property Company As ICollection(Of Company) = New HashSet(Of Company)
    Public Overridable Property Party As ICollection(Of Party) = New HashSet(Of Party)

End Class
