'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Party
    Public Property PartyID As Integer
    Public Property TenantID As System.Guid
    Public Property MainPartyID As Nullable(Of Integer)
    Public Property PartyCode As String
    Public Property PartyName As String
    Public Property DocSysNum As Nullable(Of Integer)
    Public Property Division As String
    Public Property SelEmail As String
    Public Property SelWeb As String
    Public Property SelAddress As String
    Public Property SelCity As String
    Public Property SelState As String
    Public Property SelCountry As String
    Public Property SelStateCode As String
    Public Property SelCountryCode As String
    Public Property SelPinCode As String
    Public Property SelPhCountry As String
    Public Property SelPhArea As String
    Public Property SelFaxCountry As String
    Public Property SelFaxArea As String
    Public Property SelFaxNum As String
    Public Property SelPhNum As String
    Public Property SameAsHead As Nullable(Of Boolean)
    Public Property Shipterms As String
    Public Property Payterms As String
    Public Property Transmode As String
    Public Property Insurance As String
    Public Property Discount As String
    Public Property Freight As String
    Public Property Excise As String
    Public Property SalesTax As String
    Public Property ECCRange As String
    Public Property ECCDiv As String
    Public Property ECCNum As String
    Public Property SVTNum As String
    Public Property stnum As String
    Public Property cstnum As String
    Public Property PANNum As String
    Public Property PayTermStdID As Nullable(Of Integer)
    Public Property Creditdays As Nullable(Of Short)
    Public Property perSTax As Nullable(Of Decimal)
    Public Property perExcise As Nullable(Of Decimal)
    Public Property Remark As String
    Public Property CINNum As String
    Public Property TINNum As String
    Public Property GSTIN As String
    Public Property MailingAddress As String
    Public Property CommunicAddress As String
    Public Property TaxAddressHor As String
    Public Property TaxAddressVer As String
    Public Property TCAdd As String
    Public Property TaxAreaID As Nullable(Of Integer)
    Public Property ChallanAddress As String
    Public Property FreightIns As String
    Public Property ContactPersonName As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property LastUpdatedGSTN As Nullable(Of Date)
    Public Property SearchResult As String
    Public Property GstRegType As String

    Public Overridable Property Campus As ICollection(Of Campus) = New HashSet(Of Campus)
    Public Overridable Property PartyMain As PartyMain
    Public Overridable Property Vendor As ICollection(Of Vendor) = New HashSet(Of Vendor)

End Class
