'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PostPeriod
    Public Property PostPeriodID As Integer
    Public Property TenantID As System.Guid
    Public Property FinYearID As Nullable(Of Integer)
    Public Property Month As Nullable(Of Short)
    Public Property Year As Nullable(Of Short)
    Public Property SDate As Nullable(Of Date)
    Public Property EDate As Nullable(Of Date)
    Public Property IsFinal As Nullable(Of Boolean)
    Public Property ret_pd As String

    Public Overridable Property FinYears As FinYears

End Class
