'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ValidationRule
    Public Property ValidationRuleID As Integer
    Public Property DocType As String
    Public Property Code As String
    Public Property ValidationText As String
    Public Property ResultType As String
    Public Property RuleType As String
    Public Property RuleLevel As String
    Public Property FieldName As String
    Public Property Expression As String
    Public Property ModeCSV As String
    Public Property Remark As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property LastModApp As String
    Public Property IsDisabled As Nullable(Of Boolean)

End Class
