'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vendor
    Public Property VendorID As Integer
    Public Property TenantID As System.Guid
    Public Property PartyID As Nullable(Of Integer)
    Public Property EmployeeID As Nullable(Of Integer)
    Public Property VendorClass As String
    Public Property VendorType As String
    Public Property VendorCode As String
    Public Property DocSysNum As Nullable(Of Integer)
    Public Property TimelySupply As String
    Public Property Rates As String
    Public Property Rejections As String
    Public Property Payments As String
    Public Property LastReview As Nullable(Of Date)
    Public Property Remark As String
    Public Property SuppType As Nullable(Of Short)
    Public Property LastUpdated As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property NoPOJWO As Nullable(Of Boolean)
    Public Property HRContractStart As Nullable(Of Date)
    Public Property HRContractEnd As Nullable(Of Date)
    Public Property WorkNature As String
    Public Property HRContractSvcChgPer As Nullable(Of Decimal)
    Public Property ImportAllow As Nullable(Of Boolean)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property LastModApp As String
    Public Property AllowMultiOrigInv As Nullable(Of Boolean)
    Public Property IsCorporate As Nullable(Of Boolean)
    Public Property SwiftCode As String
    Public Property IFSCNum As String
    Public Property ImportFileID As Nullable(Of System.Guid)

    Public Overridable Property Party As Party

End Class
